-- 注意：执行前需确保达梦数据库编码为 UTF-8，且用户有建表/建索引权限
-- 1. 用户表
CREATE TABLE IF NOT EXISTS T_USER (
                                      USER_ID BIGINT PRIMARY KEY,
                                      USERNAME VARCHAR(64) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(128) NOT NULL,
    PHONE VARCHAR(32),
    STATUS INT NOT NULL DEFAULT 1, -- 1:启用 0:禁用，增加默认值
    PWD_CHANGED_AT TIMESTAMP,
    LAST_LOGIN_AT TIMESTAMP,
    FAILED_COUNT INT NOT NULL DEFAULT 0, -- 登录失败次数默认0
    LOCKED_UNTIL TIMESTAMP,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 增加默认值
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

-- 2. 角色表
CREATE TABLE IF NOT EXISTS T_ROLE (
                                      ROLE_ID BIGINT PRIMARY KEY,
                                      ROLE_CODE VARCHAR(64) NOT NULL UNIQUE,
    NAME VARCHAR(128) NOT NULL,
    STATUS INT NOT NULL DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

-- 3. 权限表
CREATE TABLE IF NOT EXISTS T_PERMISSION (
                                            PERM_ID BIGINT PRIMARY KEY,
                                            PERM_CODE VARCHAR(128) NOT NULL UNIQUE,
    PERM_TYPE VARCHAR(16) NOT NULL, -- 菜单/按钮/接口
    NAME VARCHAR(128) NOT NULL,
    PATH VARCHAR(256),
    METHOD VARCHAR(16), -- GET/POST/PUT/DELETE 等
    PARENT_ID BIGINT,
    SORT INT NOT NULL DEFAULT 0,
    STATUS INT NOT NULL DEFAULT 1,
    -- 增加外键关联自身（父权限）
    CONSTRAINT FK_PERM_PARENT FOREIGN KEY (PARENT_ID) REFERENCES T_PERMISSION(PERM_ID) ON DELETE SET NULL
    );

-- 4. 用户角色关联表
CREATE TABLE IF NOT EXISTS T_USER_ROLE (
                                           USER_ID BIGINT NOT NULL,
                                           ROLE_ID BIGINT NOT NULL,
                                           PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_UR_USER FOREIGN KEY (USER_ID) REFERENCES T_USER(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_UR_ROLE FOREIGN KEY (ROLE_ID) REFERENCES T_ROLE(ROLE_ID) ON DELETE CASCADE
    );

-- 5. 角色权限关联表
CREATE TABLE IF NOT EXISTS T_ROLE_PERMISSION (
                                                 ROLE_ID BIGINT NOT NULL,
                                                 PERM_ID BIGINT NOT NULL,
                                                 PRIMARY KEY (ROLE_ID, PERM_ID),
    CONSTRAINT FK_RP_ROLE FOREIGN KEY (ROLE_ID) REFERENCES T_ROLE(ROLE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_RP_PERM FOREIGN KEY (PERM_ID) REFERENCES T_PERMISSION(PERM_ID) ON DELETE CASCADE
    );

-- 6. 用户数据范围表（区域权限）
CREATE TABLE IF NOT EXISTS T_USER_DATA_SCOPE (
                                                 USER_ID BIGINT NOT NULL,
                                                 DISTRICT_ID BIGINT NOT NULL,
                                                 PRIMARY KEY (USER_ID, DISTRICT_ID),
    CONSTRAINT FK_UDS_USER FOREIGN KEY (USER_ID) REFERENCES T_USER(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_UDS_DISTRICT FOREIGN KEY (DISTRICT_ID) REFERENCES T_DISTRICT(ID) ON DELETE CASCADE
    );

-- 7. 刷新令牌表
CREATE TABLE IF NOT EXISTS T_REFRESH_TOKEN (
                                               ID BIGINT PRIMARY KEY,
                                               USER_ID BIGINT NOT NULL,
                                               TOKEN_HASH VARCHAR(128) NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    REVOKED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IP VARCHAR(64),
    UA VARCHAR(256),
    CONSTRAINT FK_RT_USER FOREIGN KEY (USER_ID) REFERENCES T_USER(USER_ID) ON DELETE CASCADE
    );

-- 8. 审计日志表（达梦用CLOB大写，或用TEXT，这里用CLOB）
CREATE TABLE IF NOT EXISTS T_AUDIT_LOG (
                                           ID BIGINT PRIMARY KEY,
                                           USER_ID BIGINT,
                                           ACTION VARCHAR(64) NOT NULL,
    RESOURCE VARCHAR(256),
    REQUEST_CLOB CLOB, -- 达梦支持CLOB（大写）
    RESULT_CODE VARCHAR(32),
    COST_MS BIGINT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IP VARCHAR(64),
    UA VARCHAR(256),
    CONSTRAINT FK_AL_USER FOREIGN KEY (USER_ID) REFERENCES T_USER(USER_ID) ON DELETE SET NULL
    );

-- 9. 区域表
CREATE TABLE IF NOT EXISTS T_DISTRICT (
                                          ID BIGINT PRIMARY KEY,
                                          NAME VARCHAR(128) NOT NULL,
    CODE VARCHAR(64) UNIQUE -- 区域编码唯一
    );

-- 10. 街道表
CREATE TABLE IF NOT EXISTS T_STREET (
                                        ID BIGINT PRIMARY KEY,
                                        DISTRICT_ID BIGINT NOT NULL,
                                        NAME VARCHAR(128) NOT NULL,
    CODE VARCHAR(64) UNIQUE,
    CONSTRAINT FK_STREET_DISTRICT FOREIGN KEY (DISTRICT_ID) REFERENCES T_DISTRICT(ID) ON DELETE CASCADE
    );

-- 11. 字典表
CREATE TABLE IF NOT EXISTS T_DICT (
                                      DICT_TYPE VARCHAR(64) NOT NULL,
    DICT_CODE VARCHAR(64) NOT NULL,
    DICT_NAME VARCHAR(128) NOT NULL,
    SORT INT NOT NULL DEFAULT 0,
    STATUS INT NOT NULL DEFAULT 1,
    PRIMARY KEY (DICT_TYPE, DICT_CODE)
    );

-- 12. 人员表
CREATE TABLE IF NOT EXISTS T_PERSON (
                                        PERSON_ID BIGINT PRIMARY KEY,
                                        NAME VARCHAR(64) NOT NULL,
    ID_NO VARCHAR(32) NOT NULL UNIQUE, -- 身份证号唯一
    GENDER VARCHAR(8), -- 男/女/未知
    BIRTHDAY DATE,
    PHONE VARCHAR(32),
    DISTRICT_ID BIGINT,
    STREET_ID BIGINT,
    ADDRESS VARCHAR(256),
    LONGITUDE DECIMAL(10,7), -- 经度（范围：-180~180）
    LATITUDE DECIMAL(10,7), -- 纬度（范围：-90~90）
    LOCATION_ACCURACY VARCHAR(20), -- 定位精度
    LOCATION_UPDATED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PERSON_DISTRICT FOREIGN KEY (DISTRICT_ID) REFERENCES T_DISTRICT(ID) ON DELETE SET NULL,
    CONSTRAINT FK_PERSON_STREET FOREIGN KEY (STREET_ID) REFERENCES T_STREET(ID) ON DELETE SET NULL
    );

-- 13. 残疾证表
CREATE TABLE IF NOT EXISTS T_DISABILITY_CARD (
                                                 CARD_ID BIGINT PRIMARY KEY,
                                                 PERSON_ID BIGINT NOT NULL,
                                                 CARD_NO VARCHAR(64) NOT NULL UNIQUE,
    CATEGORY_CODE VARCHAR(32), -- 残疾类别编码
    LEVEL_CODE VARCHAR(32), -- 残疾等级编码
    ISSUE_DATE DATE,
    STATUS VARCHAR(16) DEFAULT 'VALID', -- 有效/失效/注销
    EXPIRE_DATE DATE,
    CANCEL_DATE DATE,
    CONSTRAINT FK_DC_PERSON FOREIGN KEY (PERSON_ID) REFERENCES T_PERSON(PERSON_ID) ON DELETE CASCADE
    );

-- 14. 车辆福利表
CREATE TABLE IF NOT EXISTS T_CAR_BENEFIT (
                                             PERSON_ID BIGINT PRIMARY KEY,
                                             HAS_CAR INT DEFAULT 0, -- 0:无 1:有（替代boolean）
                                             PLATE_NO VARCHAR(32),
    ANNUAL_INSPECTION_STATUS VARCHAR(16), -- 年检状态
    CAR_OWNER_ID_NO VARCHAR(32),
    LAST_INSPECTION_DATE DATE,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CB_PERSON FOREIGN KEY (PERSON_ID) REFERENCES T_PERSON(PERSON_ID) ON DELETE CASCADE
    );

-- 15. 医疗福利表
CREATE TABLE IF NOT EXISTS T_MEDICAL_BENEFIT (
                                                 PERSON_ID BIGINT PRIMARY KEY,
                                                 ENABLED INT DEFAULT 0, -- 0:未启用 1:启用
                                                 STATUS VARCHAR(16), -- 正常/暂停/失效
    LAST_PAY_DATE DATE,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_MB_PERSON FOREIGN KEY (PERSON_ID) REFERENCES T_PERSON(PERSON_ID) ON DELETE CASCADE
    );

-- 16. 养老金福利表
CREATE TABLE IF NOT EXISTS T_PENSION_BENEFIT (
                                                 PERSON_ID BIGINT PRIMARY KEY,
                                                 ENABLED INT DEFAULT 0, -- 0:未启用 1:启用
                                                 STATUS VARCHAR(16), -- 正常/暂停/失效
    LAST_PAY_DATE DATE,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PB_PERSON FOREIGN KEY (PERSON_ID) REFERENCES T_PERSON(PERSON_ID) ON DELETE CASCADE
    );

-- 17. 盲人证表
CREATE TABLE IF NOT EXISTS T_BLIND_CARD (
                                            PERSON_ID BIGINT PRIMARY KEY,
                                            CARD_NO VARCHAR(64) UNIQUE,
    STATUS VARCHAR(16) DEFAULT 'VALID', -- 有效/失效/注销
    ISSUE_DATE DATE,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_BC_PERSON FOREIGN KEY (PERSON_ID) REFERENCES T_PERSON(PERSON_ID) ON DELETE CASCADE
    );

-- 18. 规则表
CREATE TABLE IF NOT EXISTS T_RULE (
                                      RULE_ID BIGINT PRIMARY KEY,
                                      RULE_CODE VARCHAR(64) NOT NULL UNIQUE,
    NAME VARCHAR(128) NOT NULL,
    CATEGORY VARCHAR(64),
    ENABLED INT DEFAULT 1, -- 0:禁用 1:启用（替代boolean）
    SEVERITY VARCHAR(16), -- 严重程度：低/中/高/紧急
    PARAMS_JSON CLOB, -- 规则参数（JSON格式）
    DESCRIPTION VARCHAR(512),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

-- 19. 异常表
CREATE TABLE IF NOT EXISTS T_ANOMALY (
                                         ANOMALY_ID BIGINT PRIMARY KEY,
                                         RULE_ID BIGINT,
                                         PERSON_ID BIGINT NOT NULL,
                                         ANOMALY_TYPE VARCHAR(32) NOT NULL,
    HIT_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(16) NOT NULL DEFAULT 'UNHANDLED', -- 未处理/已处理/已忽略
    HANDLER_USER_ID BIGINT,
    HANDLE_NOTE VARCHAR(512),
    HANDLED_AT TIMESTAMP,
    CONSTRAINT FK_ANOMALY_RULE FOREIGN KEY (RULE_ID) REFERENCES T_RULE(RULE_ID) ON DELETE SET NULL,
    CONSTRAINT FK_ANOMALY_PERSON FOREIGN KEY (PERSON_ID) REFERENCES T_PERSON(PERSON_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ANOMALY_HANDLER FOREIGN KEY (HANDLER_USER_ID) REFERENCES T_USER(USER_ID) ON DELETE SET NULL
    );

-- 20. 异常快照表
CREATE TABLE IF NOT EXISTS T_ANOMALY_SNAPSHOT (
                                                  ANOMALY_ID BIGINT PRIMARY KEY,
                                                  SNAPSHOT_JSON CLOB,
                                                  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                  CONSTRAINT FK_AS_ANOMALY FOREIGN KEY (ANOMALY_ID) REFERENCES T_ANOMALY(ANOMALY_ID) ON DELETE CASCADE
    );

-- 21. 人员向量表（语义搜索）
CREATE TABLE IF NOT EXISTS T_PERSON_VECTOR (
                                               PERSON_ID BIGINT PRIMARY KEY,
                                               VECTOR CLOB, -- 向量数据（JSON/数组格式）
                                               UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                               CONSTRAINT FK_PV_PERSON FOREIGN KEY (PERSON_ID) REFERENCES T_PERSON(PERSON_ID) ON DELETE CASCADE
    );

-- 22. 异常案例表
CREATE TABLE IF NOT EXISTS T_ANOMALY_CASE (
                                              CASE_ID BIGINT PRIMARY KEY,
                                              PERSON_ID BIGINT NOT NULL,
                                              TITLE VARCHAR(256) NOT NULL,
    DESCRIPTION CLOB,
    ANOMALY_TYPE VARCHAR(64),
    SEVERITY INT DEFAULT 1, -- 1:低 2:中 3:高 4:紧急
    RESOLUTION CLOB,
    HANDLER_USER_ID BIGINT,
    RESOLVED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_AC_PERSON FOREIGN KEY (PERSON_ID) REFERENCES T_PERSON(PERSON_ID) ON DELETE CASCADE,
    CONSTRAINT FK_AC_HANDLER FOREIGN KEY (HANDLER_USER_ID) REFERENCES T_USER(USER_ID) ON DELETE SET NULL
    );

-- 23. 异常案例向量表
CREATE TABLE IF NOT EXISTS T_ANOMALY_CASE_VECTOR (
                                                     CASE_ID BIGINT PRIMARY KEY,
                                                     VECTOR CLOB,
                                                     UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                     CONSTRAINT FK_ACV_CASE FOREIGN KEY (CASE_ID) REFERENCES T_ANOMALY_CASE(CASE_ID) ON DELETE CASCADE
    );

-- 24. 政策文档主表
CREATE TABLE IF NOT EXISTS T_POLICY_DOCUMENT (
                                                 POLICY_ID BIGINT PRIMARY KEY,
                                                 USER_ID BIGINT NOT NULL,
                                                 TITLE VARCHAR(256) NOT NULL,
    OSS_URL VARCHAR(512) NOT NULL,
    OSS_KEY VARCHAR(512) NOT NULL,
    FILE_NAME VARCHAR(256),
    FILE_SIZE BIGINT,
    FILE_TYPE VARCHAR(32), -- 文件类型：pdf/docx/txt 等
    CONTENT_LENGTH INT,
    STATUS VARCHAR(16) DEFAULT 'ACTIVE', -- ACTIVE:有效 DELETED:删除
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PD_USER FOREIGN KEY (USER_ID) REFERENCES T_USER(USER_ID) ON DELETE CASCADE
    );

-- 25. 政策分析版本表
CREATE TABLE IF NOT EXISTS T_POLICY_ANALYSIS (
                                                 ANALYSIS_ID BIGINT PRIMARY KEY,
                                                 POLICY_ID BIGINT NOT NULL,
                                                 VERSION INT NOT NULL DEFAULT 1,
                                                 IS_LATEST INT DEFAULT 1, -- 0:否 1:是（替代boolean）
                                                 CONDITIONS_JSON CLOB, -- 分析条件（JSON）
                                                 EXPLANATION VARCHAR(2048),
    ANALYZED_SEGMENTS INT DEFAULT 0,
    TOTAL_SEGMENTS INT DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PA_POLICY FOREIGN KEY (POLICY_ID) REFERENCES T_POLICY_DOCUMENT(POLICY_ID) ON DELETE CASCADE,
    -- 同一政策的最新版本唯一
    CONSTRAINT UK_PA_POLICY_LATEST UNIQUE (POLICY_ID, IS_LATEST)
    );

-- 26. 政策查询记录表
CREATE TABLE IF NOT EXISTS T_POLICY_QUERY_LOG (
                                                  LOG_ID BIGINT PRIMARY KEY,
                                                  ANALYSIS_ID BIGINT NOT NULL,
                                                  FILTERS_JSON CLOB, -- 查询过滤条件（JSON）
                                                  TOTAL_RESULTS INT DEFAULT 0,
                                                  EXECUTED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                  CONSTRAINT FK_PQL_ANALYSIS FOREIGN KEY (ANALYSIS_ID) REFERENCES T_POLICY_ANALYSIS(ANALYSIS_ID) ON DELETE CASCADE
    );

-- ========== 索引（达梦索引命名规范：IDX_表名_字段名） ==========
-- 政策文档表索引
CREATE INDEX IF NOT EXISTS IDX_PD_USER ON T_POLICY_DOCUMENT(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_PD_STATUS ON T_POLICY_DOCUMENT(STATUS);
-- 政策分析表索引
CREATE INDEX IF NOT EXISTS IDX_PA_POLICY ON T_POLICY_ANALYSIS(POLICY_ID);
CREATE INDEX IF NOT EXISTS IDX_PA_LATEST ON T_POLICY_ANALYSIS(POLICY_ID, IS_LATEST);
-- 补充常用索引（提升查询性能）
CREATE INDEX IF NOT EXISTS IDX_PERSON_ID_NO ON T_PERSON(ID_NO);
CREATE INDEX IF NOT EXISTS IDX_ANOMALY_PERSON_STATUS ON T_ANOMALY(PERSON_ID, STATUS);
CREATE INDEX IF NOT EXISTS IDX_ANOMALY_HIT_TIME ON T_ANOMALY(HIT_TIME);