-- 导入治理模块数据库设计
-- 执行顺序：先执行模块配置表，再执行27个数据表

-- ============================================
-- 1. 导入模块配置表
-- ============================================

-- 模块定义表
CREATE TABLE IF NOT EXISTS T_IMPORT_MODULE (
    MODULE_CODE VARCHAR(50) PRIMARY KEY,
    MODULE_NAME VARCHAR(100) NOT NULL,
    TABLE_NAME VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(50),
    ID_CARD_FIELD VARCHAR(50) DEFAULT 'ID_CARD',
    CERT_NO_FIELD VARCHAR(50) DEFAULT 'DISABILITY_CERT_NO',
    SORT_ORDER INT DEFAULT 0,
    IS_ACTIVE INT DEFAULT 1,
    PERMISSION_CODE VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块字段定义表
CREATE TABLE IF NOT EXISTS T_IMPORT_MODULE_FIELD (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MODULE_CODE VARCHAR(50) NOT NULL,
    FIELD_CODE VARCHAR(50) NOT NULL,
    FIELD_NAME VARCHAR(100) NOT NULL,
    DB_COLUMN VARCHAR(50) NOT NULL,
    DATA_TYPE VARCHAR(20) NOT NULL,
    IS_REQUIRED INT DEFAULT 0,
    IS_UNIQUE INT DEFAULT 0,
    DEFAULT_VALUE VARCHAR(200),
    VALIDATION_RULE VARCHAR(500),
    SORT_ORDER INT DEFAULT 0,
    IS_DISPLAY INT DEFAULT 1,
    CONSTRAINT UK_MODULE_FIELD UNIQUE (MODULE_CODE, FIELD_CODE)
);

-- 扩展导入批次表
CREATE TABLE IF NOT EXISTS T_IMPORT_BATCH (
    BATCH_ID BIGINT PRIMARY KEY,
    MODULE_CODE VARCHAR(50),
    FILE_NAME VARCHAR(256),
    IMPORT_STRATEGY VARCHAR(20),
    STATUS VARCHAR(32),
    TOTAL_ROWS INT DEFAULT 0,
    SUCCESS_ROWS INT DEFAULT 0,
    FAILED_ROWS INT DEFAULT 0,
    FIELD_MAPPING CLOB,
    NOTE CLOB,
    CREATED_BY BIGINT,
    CREATED_AT TIMESTAMP,
    COMMITTED_BY BIGINT,
    COMMITTED_AT TIMESTAMP
);

-- 扩展导入行数据表
CREATE TABLE IF NOT EXISTS T_IMPORT_ROW (
    ROW_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT NOT NULL,
    ROW_NO INT,
    RAW_DATA CLOB,
    PARSED_DATA CLOB,
    MAPPED_DATA CLOB,
    ID_CARD_VALUE VARCHAR(50),
    VALIDATE_STATUS VARCHAR(20),
    ERROR_MSG VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 导入日志表
CREATE TABLE IF NOT EXISTS T_IMPORT_LOG (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BATCH_ID BIGINT NOT NULL,
    LOG_TYPE VARCHAR(20) NOT NULL,
    ROW_NO INT,
    FIELD_CODE VARCHAR(50),
    MESSAGE VARCHAR(1000) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 数据备份表
CREATE TABLE IF NOT EXISTS T_IMPORT_BACKUP (
    BACKUP_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT NOT NULL,
    MODULE_CODE VARCHAR(50) NOT NULL,
    TABLE_NAME VARCHAR(100) NOT NULL,
    RECORD_COUNT INT DEFAULT 0,
    BACKUP_DATA CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- 2. 27个模块数据表
-- ============================================

-- 模块1: 残疾人认证
CREATE TABLE IF NOT EXISTS T_IMP_DISABLED_CERT (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    AGE INT,
    GENDER VARCHAR(8),
    DISTRICT VARCHAR(50),
    STREET VARCHAR(50),
    COMMITTEE VARCHAR(50),
    HOUSEHOLD_TYPE VARCHAR(32),
    STATUS VARCHAR(32),
    DISABILITY_CATEGORY VARCHAR(32),
    DISABILITY_LEVEL VARCHAR(16),
    SIDE_TYPE VARCHAR(16),
    HOUSEHOLD_ADDRESS VARCHAR(256),
    CONTACT_ADDRESS VARCHAR(256),
    CONTACT_PHONE VARCHAR(32),
    EMPLOYMENT VARCHAR(100),
    FIRST_APPLY_DATE DATE,
    APPLY_TYPE VARCHAR(50),
    APPLY_DATE DATE,
    REMARK VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块2: 残疾管理
CREATE TABLE IF NOT EXISTS T_IMP_DISABLED_MGMT (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    HOUSEHOLD_DISTRICT VARCHAR(50),
    HOUSEHOLD_AREA VARCHAR(50),
    RESIDENCE VARCHAR(256),
    CONTACT_PHONE VARCHAR(32),
    CONTACT_ADDRESS VARCHAR(256),
    PLATE_NO VARCHAR(32),
    CAR_TYPE VARCHAR(32),
    FIRST_ISSUE_DATE DATE,
    REGISTRATION_DATE DATE,
    RESET_DATE DATE,
    DISABILITY_TYPE_CODE VARCHAR(32),
    STATUS VARCHAR(32),
    INSURANCE_STATUS VARCHAR(32),
    INSPECTION_STATUS VARCHAR(32),
    FIRST_CERT_DATE DATE,
    SUBSIDY_MONTH VARCHAR(20),
    SUBSIDY_AMOUNT DECIMAL(10,2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块3: 康复医疗/器材补助
CREATE TABLE IF NOT EXISTS T_IMP_REHAB_SUBSIDY (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    HOUSEHOLD_DISTRICT VARCHAR(50),
    HOUSEHOLD_STREET VARCHAR(50),
    DISABILITY_CATEGORY VARCHAR(32),
    DISABILITY_LEVEL VARCHAR(16),
    MEDICAL_INSURANCE_METHOD VARCHAR(50),
    ACCOUNT_INFO VARCHAR(100),
    RETURN_DATE DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块4: 养老补助
CREATE TABLE IF NOT EXISTS T_IMP_PENSION_SUBSIDY (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    ACCOUNT_DISTRICT VARCHAR(50),
    ACCOUNT_STREET VARCHAR(50),
    GENDER VARCHAR(8),
    PAY_START_MONTH VARCHAR(20),
    PAY_END_MONTH VARCHAR(20),
    SUBSIDY_AMOUNT DECIMAL(10,2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块5: 个人证管理
CREATE TABLE IF NOT EXISTS T_IMP_PERSONAL_CERT (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    PERSON_ID_CODE VARCHAR(50),
    NAME VARCHAR(64),
    APPLY_DATE DATE,
    STREET VARCHAR(50),
    ISSUE_DISTRICT VARCHAR(50),
    AUDIT_DATE DATE,
    IS_PRINTED INT DEFAULT 0,
    AGENT_CERT VARCHAR(50),
    TRACKING_NO VARCHAR(50),
    APPROVAL_STATUS VARCHAR(32),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块6: 残疾家庭情况
CREATE TABLE IF NOT EXISTS T_IMP_FAMILY_SITUATION (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    COMMITTEE VARCHAR(50),
    DISABILITY_CATEGORY VARCHAR(32),
    DISABILITY_LEVEL VARCHAR(16),
    RENOVATION_LOCATION VARCHAR(256),
    RENOVATION_TYPE VARCHAR(50),
    RENOVATION_PROGRESS VARCHAR(32),
    RENOVATION_UNIT VARCHAR(100),
    RENOVATION_AMOUNT DECIMAL(10,2),
    RENOVATION_MANAGER VARCHAR(64),
    CONTACT_PHONE VARCHAR(32),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块7: 借信卡
CREATE TABLE IF NOT EXISTS T_IMP_LOAN_CARD (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    BIRTHDAY DATE,
    HOUSEHOLD_ADDRESS VARCHAR(256),
    HOME_ADDRESS VARCHAR(256),
    CONTACT_PHONE VARCHAR(32),
    PACKAGE_TYPE VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块8: 慢性病/康护
CREATE TABLE IF NOT EXISTS T_IMP_CHRONIC_DISEASE (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    HOUSEHOLD_DISTRICT VARCHAR(50),
    HOUSEHOLD_STREET VARCHAR(50),
    DISABILITY_CATEGORY VARCHAR(32),
    AGE INT,
    SERVICE_PERSON_NAME VARCHAR(64),
    SERVICE_PERSON_BIRTHDAY DATE,
    SERVICE_PERSON_PHONE VARCHAR(32),
    SERVICE_ORGANIZATION VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块9: 机构养护
CREATE TABLE IF NOT EXISTS T_IMP_INSTITUTION_CARE (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    HOUSEHOLD_DISTRICT VARCHAR(50),
    HOUSEHOLD_STREET VARCHAR(50),
    DISABILITY_CATEGORY VARCHAR(32),
    AGE INT,
    CARE_INSTITUTION VARCHAR(100),
    CHECKIN_AUDIT_DATE DATE,
    CHECKOUT_AUDIT_DATE DATE,
    CHECKOUT_REASON VARCHAR(200),
    SUBSIDY_MONTH VARCHAR(20),
    SUBSIDY_AMOUNT DECIMAL(10,2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块10: 人工耳蜗
CREATE TABLE IF NOT EXISTS T_IMP_COCHLEAR_IMPLANT (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    STREET VARCHAR(50),
    DISABILITY_CATEGORY VARCHAR(32),
    CONTACT_PHONE VARCHAR(32),
    AGE INT,
    APPLY_DATE DATE,
    SURGERY_DATE DATE,
    ACTIVATION_DATE DATE,
    SURGERY_HOSPITAL VARCHAR(100),
    IMPLANT_EAR VARCHAR(16),
    ENABLE_EAR VARCHAR(16),
    SURGERY_AMOUNT DECIMAL(10,2),
    SELF_PAID_AMOUNT DECIMAL(10,2),
    SUBSIDY_AMOUNT DECIMAL(10,2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块11: 康复体矫
CREATE TABLE IF NOT EXISTS T_IMP_REHAB_ORTHODONTICS (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    STREET VARCHAR(50),
    DISABILITY_CATEGORY VARCHAR(32),
    CONTACT_PHONE VARCHAR(32),
    AGE INT,
    GENE_TEST_RESULT VARCHAR(200),
    APPLY_DATE DATE,
    TEST_HOSPITAL VARCHAR(100),
    TEST_DATE DATE,
    SUBSIDY_AMOUNT DECIMAL(10,2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块12: 儿童康复矫正
CREATE TABLE IF NOT EXISTS T_IMP_CHILD_REHAB (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    HOUSEHOLD_DISTRICT VARCHAR(50),
    HOUSEHOLD_STREET VARCHAR(50),
    AGE INT,
    DISABILITY_CATEGORY VARCHAR(32),
    BABY_CARD_TYPE VARCHAR(32),
    BIRTHDAY DATE,
    APPLY_DATE DATE,
    EVALUATION_HOSPITAL VARCHAR(100),
    REHAB_INSTITUTION VARCHAR(100),
    INSTITUTION_ADDRESS VARCHAR(256),
    SUBSIDY_AMOUNT DECIMAL(10,2),
    SUBSIDY_AGE VARCHAR(20),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块13: 交通补贴
CREATE TABLE IF NOT EXISTS T_IMP_TRAFFIC_SUBSIDY (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    PREPAY_MONTH VARCHAR(20),
    BACKPAY_MONTH VARCHAR(20),
    SUBSIDY_AMOUNT DECIMAL(10,2),
    HOUSEHOLD_ADDRESS VARCHAR(256),
    HOUSEHOLD_COMMITTEE VARCHAR(50),
    CONTACT_PHONE VARCHAR(32),
    DISABILITY_ROLE VARCHAR(32),
    SOURCE VARCHAR(50),
    BANK_NAME VARCHAR(100),
    BANK_BRANCH VARCHAR(100),
    ACCOUNT_NAME VARCHAR(64),
    BANK_ACCOUNT VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块14: 精准帮扶
CREATE TABLE IF NOT EXISTS T_IMP_PRECISE_HELP (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    SUBSIDY_AMOUNT DECIMAL(10,2),
    IS_VISITED INT DEFAULT 0,
    ACCOUNT_NAME VARCHAR(64),
    BANK_NAME VARCHAR(100),
    BANK_BRANCH VARCHAR(100),
    BANK_ACCOUNT VARCHAR(50),
    SUBSIDY_REASON VARCHAR(100),
    SUBSIDY_REASON_DESC VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块15: 残疾人（人/团体申请）
CREATE TABLE IF NOT EXISTS T_IMP_DISABLED_APPLICATION (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    HOUSEHOLD_DISTRICT VARCHAR(50),
    HOUSEHOLD_STREET VARCHAR(50),
    DISABILITY_CATEGORY VARCHAR(32),
    DISABILITY_LEVEL VARCHAR(16),
    AGE INT,
    ITEM_NAME VARCHAR(100),
    PUSH_TIME TIMESTAMP,
    INTENTION VARCHAR(200),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块16: 辅助器具
CREATE TABLE IF NOT EXISTS T_IMP_ASSISTIVE_DEVICE (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    PROGRESS VARCHAR(32),
    APPLY_SOURCE VARCHAR(50),
    APPLY_ORDER_NO VARCHAR(50),
    ORDER_NO VARCHAR(50),
    HOUSEHOLD_DISTRICT VARCHAR(50),
    HOUSEHOLD_STREET VARCHAR(50),
    DISABILITY_CATEGORY VARCHAR(32),
    DISABILITY_LEVEL VARCHAR(16),
    DISABILITY_PART VARCHAR(32),
    EVALUATION_RESULT VARCHAR(100),
    RECEIVER_NAME VARCHAR(64),
    RECEIVER_PHONE VARCHAR(32),
    RECEIVER_ADDRESS VARCHAR(256),
    APPLY_DATE DATE,
    AUDIT_DATE DATE,
    RECEIVE_DATE DATE,
    APPLY_STATUS VARCHAR(32),
    APPLY_APPROVED VARCHAR(32),
    HOUSEHOLD_ADDRESS VARCHAR(256),
    SUBSIDY_AMOUNT DECIMAL(10,2),
    UNIT_AMOUNT DECIMAL(10,2),
    PERSONAL_AMOUNT DECIMAL(10,2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块17: 体检
CREATE TABLE IF NOT EXISTS T_IMP_HEALTH_CHECK (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    HOUSEHOLD_DISTRICT VARCHAR(50),
    HOUSEHOLD_STREET VARCHAR(50),
    DISABILITY_CATEGORY VARCHAR(32),
    DISABILITY_LEVEL VARCHAR(16),
    AGE INT,
    CHECK_INSTITUTION VARCHAR(100),
    CHECK_DATE DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块18: 两项补贴
CREATE TABLE IF NOT EXISTS T_IMP_TWO_SUBSIDIES (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    HOUSEHOLD_DISTRICT VARCHAR(50),
    HOUSEHOLD_STREET VARCHAR(50),
    DISABILITY_CATEGORY VARCHAR(32),
    DISABILITY_LEVEL VARCHAR(16),
    AGE INT,
    APPLY_TIME TIMESTAMP,
    SUBSIDY_TYPE VARCHAR(32),
    SUBSIDY_STANDARD VARCHAR(50),
    SUBSIDY_AMOUNT DECIMAL(10,2),
    STATUS VARCHAR(32),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块19: 就业
CREATE TABLE IF NOT EXISTS T_IMP_EMPLOYMENT (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    GENDER VARCHAR(8),
    DISABILITY_LEVEL VARCHAR(16),
    EMPLOYMENT_STATUS VARCHAR(32),
    INDUSTRY VARCHAR(50),
    EMPLOYMENT_CHANNEL VARCHAR(50),
    UNEMPLOYMENT_REASON VARCHAR(100),
    COMPANY_NAME VARCHAR(100),
    LABOR_CONTRACT VARCHAR(32),
    FIXED_TERM_CONTRACT VARCHAR(32),
    START_TIME DATE,
    END_TIME DATE,
    EMPLOYMENT_FORMAT VARCHAR(32),
    SELF_CARE_ABILITY VARCHAR(32),
    EMPLOYMENT_WILL VARCHAR(32),
    HOUSEHOLD_ADDRESS VARCHAR(256),
    HOUSEHOLD_STREET VARCHAR(50),
    HOUSEHOLD_COMMITTEE VARCHAR(50),
    CONTACT_PHONE VARCHAR(32),
    MOBILE_PHONE VARCHAR(32),
    TELEPHONE VARCHAR(32),
    INPUT_AREA VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块20: 职业技能培训
CREATE TABLE IF NOT EXISTS T_IMP_VOCATIONAL_TRAINING (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    DISABILITY_CATEGORY VARCHAR(32),
    DISABILITY_LEVEL VARCHAR(16),
    AGE INT,
    HOUSEHOLD_ADDRESS VARCHAR(256),
    TRAINING_PROJECT_NAME VARCHAR(100),
    COURSE_CATEGORY VARCHAR(50),
    TRAINING_LEVEL VARCHAR(32),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块21: 阳光机构
CREATE TABLE IF NOT EXISTS T_IMP_SUNSHINE_INSTITUTION (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    SUNSHINE_PLACE VARCHAR(100),
    REGISTER_DATE DATE,
    VALID_STATUS VARCHAR(32),
    DISTRICT VARCHAR(50),
    STREET VARCHAR(50),
    INSTITUTION_NAME VARCHAR(100),
    GENDER VARCHAR(8),
    AGE INT,
    DISABILITY_CATEGORY VARCHAR(32),
    DISABILITY_LEVEL VARCHAR(16),
    BIRTHDAY DATE,
    MONTH VARCHAR(20),
    DATA_SOURCE VARCHAR(32),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块22: 残疾人基本状况调查
CREATE TABLE IF NOT EXISTS T_IMP_BASIC_SURVEY (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    ADDRESS VARCHAR(256),
    MARITAL_STATUS VARCHAR(32),
    CONTACT_NAME VARCHAR(64),
    CONTACT_RELATION VARCHAR(32),
    IS_IN_INSTITUTION INT DEFAULT 0,
    RESIDENCE_INFO VARCHAR(256),
    FAMILY_ECONOMY VARCHAR(50),
    DISABILITY_STATUS VARCHAR(200),
    EMPLOYMENT_STATUS VARCHAR(200),
    SOCIAL_SECURITY VARCHAR(200),
    HEALTH_STATUS VARCHAR(200),
    REHAB_SERVICE VARCHAR(200),
    CULTURE_SPORTS VARCHAR(200),
    FAMILY_STRUCTURE VARCHAR(100),
    HOUSEHOLDER_NAME VARCHAR(64),
    HOUSEHOLDER_ID_CARD VARCHAR(18),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块23: 美伦车
CREATE TABLE IF NOT EXISTS T_IMP_MEILUN_CAR (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    STREET VARCHAR(50),
    GENDER VARCHAR(8),
    DISABILITY_LEVEL VARCHAR(16),
    HOUSEHOLD_ADDRESS VARCHAR(256),
    RESIDENCE_ADDRESS VARCHAR(256),
    POSTAL_CODE VARCHAR(10),
    TELEPHONE VARCHAR(32),
    MOBILE_PHONE VARCHAR(32),
    BANK_NAME VARCHAR(100),
    BANK_ACCOUNT VARCHAR(50),
    APPLY_DATE DATE,
    REMARK VARCHAR(500),
    SUBSIDY_AMOUNT DECIMAL(10,2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块24: 助学
CREATE TABLE IF NOT EXISTS T_IMP_EDUCATION_AID (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    AGE INT,
    GENDER VARCHAR(8),
    SCHOOL VARCHAR(100),
    MAJOR VARCHAR(100),
    CONTACT_PHONE VARCHAR(32),
    HOUSEHOLD_ADDRESS VARCHAR(256),
    RESIDENCE_ADDRESS VARCHAR(256),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块25: 节日慰问金
CREATE TABLE IF NOT EXISTS T_IMP_FESTIVAL_CONDOLENCE (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    CONDOLENCE_TYPE VARCHAR(32),
    COMMITTEE VARCHAR(50),
    DISABILITY_CATEGORY VARCHAR(32),
    ILLNESS_SITUATION VARCHAR(200),
    CONTACT_PHONE VARCHAR(32),
    RESIDENCE_ADDRESS VARCHAR(256),
    AMOUNT DECIMAL(10,2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块26: 临时困难金
CREATE TABLE IF NOT EXISTS T_IMP_TEMPORARY_AID (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    STREET VARCHAR(50),
    RECEIVER_NAME VARCHAR(64),
    RECEIVER_ACCOUNT VARCHAR(50),
    RECEIVER_BANK VARCHAR(100),
    RECEIVER_BRANCH VARCHAR(100),
    AMOUNT DECIMAL(10,2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 模块27: 结对帮扶
CREATE TABLE IF NOT EXISTS T_IMP_PAIRING_HELP (
    RECORD_ID BIGINT PRIMARY KEY,
    BATCH_ID BIGINT,
    PERSON_ID BIGINT,
    ID_CARD VARCHAR(18),
    DISABILITY_CERT_NO VARCHAR(20),
    NAME VARCHAR(64),
    GENDER VARCHAR(8),
    HOUSEHOLD_ADDRESS VARCHAR(256),
    HOME_ADDRESS VARCHAR(256),
    MARITAL_STATUS VARCHAR(32),
    EMPLOYMENT_STATUS VARCHAR(32),
    FAMILY_SITUATION VARCHAR(200),
    HELP_REASON VARCHAR(200),
    HELP_TYPE VARCHAR(50),
    PERSON_TYPE VARCHAR(32),
    PERSONAL_ECONOMY VARCHAR(50),
    FAMILY_ECONOMY VARCHAR(50),
    OTHER_ISSUES VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- 3. 索引
-- ============================================

CREATE INDEX IF NOT EXISTS IDX_IMP_BATCH_MODULE ON T_IMPORT_BATCH(MODULE_CODE);
CREATE INDEX IF NOT EXISTS IDX_IMP_BATCH_STATUS ON T_IMPORT_BATCH(STATUS);
CREATE INDEX IF NOT EXISTS IDX_IMP_ROW_BATCH ON T_IMPORT_ROW(BATCH_ID);
CREATE INDEX IF NOT EXISTS IDX_IMP_LOG_BATCH ON T_IMPORT_LOG(BATCH_ID);

-- 为所有模块表创建ID_CARD索引
CREATE INDEX IF NOT EXISTS IDX_IMP_DC_ID_CARD ON T_IMP_DISABLED_CERT(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_DM_ID_CARD ON T_IMP_DISABLED_MGMT(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_RS_ID_CARD ON T_IMP_REHAB_SUBSIDY(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_PS_ID_CARD ON T_IMP_PENSION_SUBSIDY(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_PC_ID_CARD ON T_IMP_PERSONAL_CERT(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_FS_ID_CARD ON T_IMP_FAMILY_SITUATION(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_LC_ID_CARD ON T_IMP_LOAN_CARD(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_CD_ID_CARD ON T_IMP_CHRONIC_DISEASE(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_IC_ID_CARD ON T_IMP_INSTITUTION_CARE(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_CI_ID_CARD ON T_IMP_COCHLEAR_IMPLANT(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_RO_ID_CARD ON T_IMP_REHAB_ORTHODONTICS(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_CR_ID_CARD ON T_IMP_CHILD_REHAB(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_TS_ID_CARD ON T_IMP_TRAFFIC_SUBSIDY(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_PH_ID_CARD ON T_IMP_PRECISE_HELP(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_DA_ID_CARD ON T_IMP_DISABLED_APPLICATION(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_AD_ID_CARD ON T_IMP_ASSISTIVE_DEVICE(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_HC_ID_CARD ON T_IMP_HEALTH_CHECK(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_2S_ID_CARD ON T_IMP_TWO_SUBSIDIES(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_EM_ID_CARD ON T_IMP_EMPLOYMENT(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_VT_ID_CARD ON T_IMP_VOCATIONAL_TRAINING(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_SI_ID_CARD ON T_IMP_SUNSHINE_INSTITUTION(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_BS_ID_CARD ON T_IMP_BASIC_SURVEY(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_MC_ID_CARD ON T_IMP_MEILUN_CAR(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_EA_ID_CARD ON T_IMP_EDUCATION_AID(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_FC_ID_CARD ON T_IMP_FESTIVAL_CONDOLENCE(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_TA_ID_CARD ON T_IMP_TEMPORARY_AID(ID_CARD);
CREATE INDEX IF NOT EXISTS IDX_IMP_PX_ID_CARD ON T_IMP_PAIRING_HELP(ID_CARD);
