-- DM8 schema for zr-platform.
-- Notes:
-- - Run in an empty schema/user (or drop existing objects manually).
-- - IDs are generated by the application (no sequences required).
-- - JSON payloads are stored as CLOB.

-- =========================
-- System / RBAC
-- =========================

create table t_user (
  user_id            number(19) primary key,
  username           varchar(64) not null,
  password_hash      varchar(255) not null,
  display_name       varchar(128) not null,
  phone              varchar(32),
  status             number(10) not null,
  pwd_changed_at     timestamp,
  last_login_at      timestamp,
  failed_count       number(10) not null,
  locked_until       timestamp,
  created_at         timestamp not null,
  updated_at         timestamp not null
);

create unique index ux_user_username on t_user(username);

create table t_role (
  role_id            number(19) primary key,
  role_code          varchar(64) not null,
  name               varchar(128) not null,
  status             number(10) not null,
  created_at         timestamp not null
);

create unique index ux_role_role_code on t_role(role_code);

create table t_permission (
  perm_id            number(19) primary key,
  perm_code          varchar(128) not null,
  perm_type          varchar(16) not null,
  name               varchar(128) not null,
  path               varchar(256),
  method             varchar(16),
  parent_id          number(19),
  sort               number(10) not null,
  status             number(10) not null
);

create unique index ux_perm_perm_code on t_permission(perm_code);
create index ix_perm_parent on t_permission(parent_id);

create table t_user_role (
  user_id            number(19) not null,
  role_id            number(19) not null,
  constraint pk_user_role primary key (user_id, role_id)
);

create index ix_user_role_user on t_user_role(user_id);
create index ix_user_role_role on t_user_role(role_id);

create table t_role_permission (
  role_id            number(19) not null,
  perm_id            number(19) not null,
  constraint pk_role_perm primary key (role_id, perm_id)
);

create index ix_role_perm_role on t_role_permission(role_id);
create index ix_role_perm_perm on t_role_permission(perm_id);

create table t_user_data_scope (
  user_id            number(19) not null,
  district_id        number(19) not null,
  constraint pk_user_scope primary key (user_id, district_id)
);

create index ix_user_scope_user on t_user_data_scope(user_id);
create index ix_user_scope_district on t_user_data_scope(district_id);

create table t_refresh_token (
  id                 number(19) primary key,
  user_id            number(19) not null,
  token_hash         varchar(128) not null,
  expires_at         timestamp not null,
  revoked_at         timestamp,
  created_at         timestamp not null,
  ip                 varchar(64),
  ua                 varchar(256)
);

create unique index ux_refresh_token_hash on t_refresh_token(token_hash);
create index ix_refresh_user on t_refresh_token(user_id);

create table t_audit_log (
  id                 number(19) primary key,
  user_id            number(19),
  action             varchar(64) not null,
  resource           varchar(256),
  request_clob       clob,
  result_code        varchar(32),
  cost_ms            number(19),
  created_at         timestamp not null,
  ip                 varchar(64),
  ua                 varchar(256)
);

create index ix_audit_user on t_audit_log(user_id);
create index ix_audit_created_at on t_audit_log(created_at);

-- =========================
-- Dictionaries
-- =========================

create table t_district (
  id                 number(19) primary key,
  name               varchar(128) not null,
  code               varchar(64)
);

create table t_street (
  id                 number(19) primary key,
  district_id        number(19) not null,
  name               varchar(128) not null,
  code               varchar(64)
);

create index ix_street_district on t_street(district_id);

create table t_dict (
  dict_type          varchar(64) not null,
  dict_code          varchar(64) not null,
  dict_name          varchar(128) not null,
  sort               number(10) not null,
  status             number(10) not null,
  constraint pk_dict primary key (dict_type, dict_code)
);

-- =========================
-- Person domain
-- =========================

create table t_person (
  person_id          number(19) primary key,
  name               varchar(64) not null,
  id_no              varchar(32) not null,
  gender             varchar(8),
  birthday           date,
  phone              varchar(32),
  district_id        number(19),
  street_id          number(19),
  address            varchar(256),
  created_at         timestamp not null,
  updated_at         timestamp not null
);

create index ix_person_district on t_person(district_id);
create index ix_person_street on t_person(street_id);
create index ix_person_id_no on t_person(id_no);

create table t_disability_card (
  card_id            number(19) primary key,
  person_id          number(19) not null,
  card_no            varchar(64) not null,
  category_code      varchar(32),
  level_code         varchar(32),
  issue_date         date,
  status             varchar(16),
  expire_date        date,
  cancel_date        date
);

create index ix_disability_card_person on t_disability_card(person_id);
create index ix_disability_card_status on t_disability_card(status);
create index ix_disability_card_cat_lvl on t_disability_card(category_code, level_code);

-- =========================
-- Business cards
-- =========================

create table t_car_benefit (
  person_id                number(19) primary key,
  has_car                  number(1),
  plate_no                 varchar(32),
  annual_inspection_status varchar(16),
  car_owner_id_no          varchar(32),
  last_inspection_date     date,
  updated_at               timestamp
);

create table t_medical_benefit (
  person_id          number(19) primary key,
  enabled            number(1),
  status             varchar(16),
  last_pay_date      date,
  updated_at         timestamp
);

create table t_pension_benefit (
  person_id          number(19) primary key,
  enabled            number(1),
  status             varchar(16),
  last_pay_date      date,
  updated_at         timestamp
);

create table t_blind_card (
  person_id          number(19) primary key,
  card_no            varchar(64),
  status             varchar(16),
  issue_date         date,
  updated_at         timestamp
);

create table t_subsidy_payment (
  payment_id         number(19) primary key,
  person_id          number(19) not null,
  subsidy_type       varchar(32) not null,
  pay_month          varchar(7) not null,
  amount             number(19,2) not null,
  pay_date           date,
  status             varchar(16),
  source_batch_id    number(19)
);

create index ix_payment_person on t_subsidy_payment(person_id);
create index ix_payment_type_month on t_subsidy_payment(subsidy_type, pay_month);

-- =========================
-- Rules / anomalies
-- =========================

create table t_rule (
  rule_id            number(19) primary key,
  rule_code          varchar(64) not null,
  name               varchar(128) not null,
  category           varchar(64),
  enabled            number(1),
  severity           varchar(16),
  params_json        clob,
  description        varchar(512),
  updated_at         timestamp
);

create unique index ux_rule_code on t_rule(rule_code);

create table t_anomaly (
  anomaly_id         number(19) primary key,
  rule_id            number(19),
  person_id          number(19) not null,
  anomaly_type       varchar(32) not null,
  hit_time           timestamp not null,
  status             varchar(16) not null,
  handler_user_id    number(19),
  handle_note        varchar(512),
  handled_at         timestamp
);

create index ix_anomaly_person on t_anomaly(person_id);
create index ix_anomaly_type on t_anomaly(anomaly_type);
create index ix_anomaly_status on t_anomaly(status);
create index ix_anomaly_hit_time on t_anomaly(hit_time);

create table t_anomaly_snapshot (
  anomaly_id         number(19) primary key,
  snapshot_json      clob,
  created_at         timestamp not null
);

-- =========================
-- Import / data quality
-- =========================

create table t_import_batch (
  batch_id           number(19) primary key,
  import_type        varchar(32) not null,
  file_name          varchar(256) not null,
  status             varchar(16) not null,
  created_by         number(19),
  created_at         timestamp not null
);

create index ix_import_batch_type on t_import_batch(import_type);
create index ix_import_batch_created_at on t_import_batch(created_at);

create table t_import_row (
  row_id             number(19) primary key,
  batch_id           number(19) not null,
  row_no             number(10) not null,
  data_json          clob,
  validate_status    varchar(16) not null,
  error_msg          varchar(512)
);

create index ix_import_row_batch on t_import_row(batch_id);

create table t_quality_issue (
  issue_id           number(19) primary key,
  issue_type         varchar(32) not null,
  person_id          number(19),
  detail_json        clob,
  status             varchar(16) not null,
  created_at         timestamp not null
);

create index ix_quality_type on t_quality_issue(issue_type);
create index ix_quality_person on t_quality_issue(person_id);
create index ix_quality_created_at on t_quality_issue(created_at);
